(() => {
  'use strict';
  const X=window.CRMV2,S=X.state,$=X.$;

  X.filterContacts=()=>{
    const f=S.filters,term=X.normalizeText(f.search);
    let list=S.contacts.filter(c=>{
      if(term){const hay=X.normalizeText([c.name,c.phoneOriginal,c.phone,c.contacted?'sim':'não',c.numberStatus,c.country,c.state,c.ddd,c.familyRef,c.activity,c.category,c.tags,c.confidence,c.duplicate?'sim':'não',c.organization,c.originalNote,c.email,c.contactNote,c.prospectStatus].join(' '));if(!hay.includes(term))return false}
      if(!X.textMatch(c.name,f.name,f.nameMode))return false;
      if(!X.phoneMatch(c.phoneOriginal,f.phoneOriginal)||!X.phoneMatch(c.phone,f.phone))return false;
      if(f.contacted==='yes'&&!c.contacted||f.contacted==='no'&&c.contacted)return false;
      if(f.numberStatus&&c.numberStatus!==f.numberStatus||f.country&&c.country!==f.country||f.state&&c.state!==f.state||f.ddd&&c.ddd!==f.ddd)return false;
      if(f.family&&c.familyRef!==f.family||f.activity&&c.activity!==f.activity||f.category&&c.category!==f.category)return false;
      if(!X.textMatch(c.tags,f.tags)||f.confidence&&c.confidence!==f.confidence)return false;
      if(f.duplicate==='yes'&&!c.duplicate||f.duplicate==='no'&&c.duplicate)return false;
      if(!X.textMatch(c.organization,f.organization)||!X.textMatch(c.originalNote,f.originalNote)||!X.textMatch(c.email,f.email)||!X.textMatch(c.contactNote,f.contactNote))return false;
      if(f.prospectStatus&&c.prospectStatus!==f.prospectStatus||!X.nextContactMatch(c.nextContact,f.nextContact))return false;
      return true
    });
    const collate=(a,b)=>String(a||'').localeCompare(String(b||''),'pt-BR',{numeric:true,sensitivity:'base'}),byName=(a,b)=>collate(a.name,b.name);
    const sorters={az:byName,za:(a,b)=>-byName(a,b),state:(a,b)=>collate(a.state,b.state)||byName(a,b),ddd:(a,b)=>collate(a.ddd,b.ddd)||byName(a,b),country:(a,b)=>collate(a.country,b.country)||byName(a,b),activity:(a,b)=>collate(a.activity,b.activity)||byName(a,b),category:(a,b)=>collate(a.category,b.category)||byName(a,b),contacted:(a,b)=>Number(a.contacted)-Number(b.contacted)||byName(a,b),newest:(a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0),oldest:(a,b)=>new Date(a.updatedAt||0)-new Date(b.updatedAt||0),next:(a,b)=>{if(!a.nextContact&&!b.nextContact)return byName(a,b);if(!a.nextContact)return 1;if(!b.nextContact)return-1;return new Date(a.nextContact)-new Date(b.nextContact)}};
    list.sort(sorters[f.sort]||byName);S.filtered=list;const max=Math.max(1,Math.ceil(list.length/X.PAGE_SIZE));if(S.page>max)S.page=max
  };
  X.statusClass=(s='')=>`status-${s.replace(/\s+/g,'-')}`;
  X.phoneHref=(p='')=>X.digits(p)?`tel:+${X.digits(p)}`:'#';
  X.whatsappHref=(p='')=>X.digits(p)?`https://wa.me/${X.digits(p)}`:'#';
  X.contactCard=c=>{const badges=[];if(c.country)badges.push(`<span class="badge blue">${X.escapeHtml(c.country)}</span>`);if(c.state)badges.push(`<span class="badge">${X.escapeHtml(c.state)}</span>`);if(c.ddd)badges.push(`<span class="badge">DDD ${X.escapeHtml(c.ddd)}</span>`);if(c.familyRef)badges.push(`<span class="badge amber">${X.escapeHtml(c.familyRef)}</span>`);if(c.activity)badges.push(`<span class="badge green">${X.escapeHtml(c.activity)}</span>`);if(c.category&&c.category!=='Sem categoria')badges.push(`<span class="badge">${X.escapeHtml(c.category)}</span>`);const checked=S.selected.has(c.id)?'checked':'',phone=c.phone||c.phoneOriginal||'';return `<article class="contact-card"><div class="select-cell"><input class="contact-select" type="checkbox" data-select-contact="${X.escapeHtml(c.id)}" ${checked}></div><div class="contact-main"><div class="contact-top"><div><div class="contact-name">${X.escapeHtml(c.name)}</div><div class="contact-phone">${X.escapeHtml(phone||'Sem telefone')}</div></div><button class="status-pill ${X.statusClass(c.prospectStatus)}" data-cycle-status="${X.escapeHtml(c.id)}">${X.escapeHtml(c.prospectStatus||'Não contatado')}</button></div><div class="contact-meta">${badges.join('')}</div><div class="contact-actions">${phone?`<a class="action-link whatsapp" href="${X.whatsappHref(phone)}" target="_blank" rel="noopener">WhatsApp</a><a class="action-link" href="${X.phoneHref(phone)}">Ligar</a>`:''}<button class="contacted-toggle ${c.contacted?'on':''}" data-toggle-contacted="${X.escapeHtml(c.id)}">${c.contacted?'✓ Contatado':'Marcar contato'}</button><button class="details-btn" data-open-details="${X.escapeHtml(c.id)}">Detalhes</button></div>${c.nextContact?`<div class="next-contact">Retornar: ${X.displayDate(c.nextContact)}</div>`:''}${c.contactNote?`<div class="contact-note-preview">${X.escapeHtml(c.contactNote)}</div>`:''}</div></article>`};
  X.renderStats=()=>{const b=S.contacts;$('statTotal').textContent=b.length;$('statPending').textContent=b.filter(c=>!c.contacted).length;$('statContacted').textContent=b.filter(c=>c.contacted).length;$('statReturn').textContent=b.filter(c=>c.prospectStatus==='Retornar').length;$('statInterested').textContent=b.filter(c=>c.prospectStatus==='Interessado').length};
  X.FILTER_LABELS={name:'Nome',phoneOriginal:'Telefone original',phone:'Telefone normalizado',contacted:'Já contatei',numberStatus:'Status do número',country:'País',state:'UF',ddd:'DDD',family:'Referência',activity:'Profissão',category:'Categoria',tags:'Tags',confidence:'Confiança',duplicate:'Duplicado',organization:'Organização',originalNote:'Observação original',email:'E-mail',contactNote:'Observação do contato',prospectStatus:'Status CRM',nextContact:'Próximo contato'};
  X.renderActiveFilters=()=>{const entries=Object.entries(S.filters).filter(([k,v])=>!['search','sort','nameMode'].includes(k)&&v).map(([k,v])=>({key:k,label:X.FILTER_LABELS[k]||k,value:v==='yes'?'Sim':v==='no'?'Não':v}));const box=$('activeFilters'),badge=$('filterCountBadge');badge.textContent=entries.length;badge.classList.toggle('hidden',!entries.length);box.classList.toggle('hidden',!entries.length);box.innerHTML=entries.map(e=>`<span class="filter-chip">${X.escapeHtml(e.label)}: ${X.escapeHtml(e.value)} <button data-remove-filter="${X.escapeHtml(e.key)}">×</button></span>`).join('')};
  X.renderBulkBar=()=>{$('bulkCount').textContent=S.selected.size;$('bulkBar').classList.toggle('hidden',S.selected.size===0)};
  X.renderList=()=>{X.filterContacts();X.renderStats();X.renderActiveFilters();X.renderBulkBar();$('resultCount').textContent=`${S.filtered.length.toLocaleString('pt-BR')} ${S.filtered.length===1?'contato':'contatos'}`;const labels={az:'A→Z',za:'Z→A',state:'UF',ddd:'DDD',country:'País',activity:'Profissão',category:'Categoria',contacted:'Pendentes',newest:'Recentes',oldest:'Antigos',next:'Retorno'};$('sortBtn').textContent=labels[S.filters.sort]||'A→Z';const list=$('contactsList'),empty=$('emptyState');if(!S.filtered.length){list.innerHTML='';empty.classList.remove('hidden');$('emptyMessage').textContent=S.contacts.length?'Nenhum contato corresponde aos filtros atuais.':'Importe sua planilha para começar.';$('pagination').classList.add('hidden');return}empty.classList.add('hidden');const start=(S.page-1)*X.PAGE_SIZE,rows=S.filtered.slice(start,start+X.PAGE_SIZE);list.innerHTML=rows.map(X.contactCard).join('');const pages=Math.ceil(S.filtered.length/X.PAGE_SIZE);$('pageInfo').textContent=`Página ${S.page} de ${pages}`;$('prevPageBtn').disabled=S.page<=1;$('nextPageBtn').disabled=S.page>=pages;$('pagination').classList.toggle('hidden',pages<=1)};
  X.openSheet=id=>{$('sheetBackdrop').classList.remove('hidden');const el=$(id);el.classList.add('open');el.setAttribute('aria-hidden','false')};
  X.closeSheets=()=>{$('sheetBackdrop').classList.add('hidden');X.qsa('.sheet.open').forEach(el=>{el.classList.remove('open');el.setAttribute('aria-hidden','true')})};
  X.contactById=id=>S.contacts.find(c=>c.id===id);
  X.updateContact=async(id,patch)=>{const idx=S.contacts.findIndex(c=>c.id===id);if(idx<0)return;const updated={...S.contacts[idx],...patch,updatedAt:X.nowIso()};S.contacts[idx]=updated;await X.dbPut(updated);X.renderList()};
  X.toggleContacted=async id=>{const c=X.contactById(id);if(!c)return;const contacted=!c.contacted;await X.updateContact(id,{contacted,lastContact:contacted?X.nowIso():c.lastContact,prospectStatus:contacted&&c.prospectStatus==='Não contatado'?'Falou comigo':c.prospectStatus});X.toast(contacted?'Contato marcado como realizado.':'Contato marcado como pendente.')};
  X.cycleStatus=async id=>{const c=X.contactById(id);if(!c)return;const current=Math.max(0,X.STATUS_OPTIONS.indexOf(c.prospectStatus)),next=X.STATUS_OPTIONS[(current+1)%X.STATUS_OPTIONS.length],patch={prospectStatus:next};if(next!=='Não contatado'&&!c.contacted){patch.contacted=true;patch.lastContact=X.nowIso()}await X.updateContact(id,patch)};
})();